version: '3'

services:
  server:
    build:
      context: ./docker/webserver
    container_name: server
    ports:
      - 80:80
    volumes:
      - ./project:/var/www/html

  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    volumes:
      - ./docker/db/mongo:/etc/mongo
